<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;

class BladeDocsController extends Controller
{
    public function index()
    {
        $groups = [
            'Public' => [
                [
                    'id' => 'landing',
                    'method' => 'GET',
                    'uri' => '/',
                    'name' => 'landing',
                    'middleware' => ['public'],
                    'view' => 'landing.blade.php',
                    'controller' => 'Web\LandingWebController',
                    'action' => 'index',
                    'description' => 'Public HIMATIK profile and recruitment landing page. It includes the interactive Department/Biro selector with agenda and program kerja details.',
                    'variables' => [
                        ['name' => '$departments', 'type' => 'Collection<Departmentsbiro>', 'description' => 'Active public departments/biros with safe fields plus eager-loaded agendas and workPrograms. Blade infers Biro/Departemen from the name and renders one selected detail panel at a time.'],
                    ],
                    'models' => ['Departmentsbiro', 'DepartmentAgenda', 'DepartmentWorkProgram'],
                    'post_fields' => [],
                ],
                [
                    'id' => 'announcements',
                    'method' => 'GET',
                    'uri' => '/announcements',
                    'name' => 'public.announcements',
                    'middleware' => ['public'],
                    'view' => 'public/announcements.blade.php',
                    'controller' => 'Web\PublicAnnouncementController',
                    'action' => 'showAcceptedList',
                    'description' => 'Public announcement board listing published accepted candidates.',
                    'variables' => [
                        ['name' => '$announcements', 'type' => 'Collection<Announcement>', 'description' => 'Accepted and published announcements with candidate and department relations.'],
                    ],
                    'models' => ['Announcement', 'Candidate', 'Departmentsbiro'],
                    'post_fields' => [],
                ],
            ],
            'Guest Only' => [
                [
                    'id' => 'login',
                    'method' => 'GET',
                    'uri' => '/login',
                    'name' => 'login',
                    'middleware' => ['guest'],
                    'view' => 'auth/login.blade.php',
                    'controller' => 'Web\AuthWebController',
                    'action' => 'showLoginForm',
                    'description' => 'Login page for all roles. Candidate redirects depend on email verification and registration completion state.',
                    'variables' => [],
                    'models' => ['User'],
                    'post_fields' => [
                        ['name' => 'email', 'type' => 'string', 'rules' => 'required|email', 'description' => 'Registered email address'],
                        ['name' => 'password', 'type' => 'string', 'rules' => 'required|string', 'description' => 'Account password'],
                    ],
                    'post_route' => 'POST /login -> AuthWebController@login',
                ],
                [
                    'id' => 'register-stage1',
                    'method' => 'GET',
                    'uri' => '/register',
                    'name' => 'user.register.view',
                    'middleware' => ['guest'],
                    'view' => 'auth/register.blade.php',
                    'controller' => 'Web\CandidateWebController',
                    'action' => 'showUserRegisterForm',
                    'description' => 'Candidate account registration step. Successful registration sends OTP and signs the user in.',
                    'variables' => [],
                    'models' => ['User'],
                    'post_fields' => [
                        ['name' => 'nama', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Full name'],
                        ['name' => 'email', 'type' => 'string', 'rules' => 'required|email|unique:users', 'description' => 'Email address'],
                        ['name' => 'password', 'type' => 'string', 'rules' => 'required|min:8|confirmed', 'description' => 'Password'],
                        ['name' => 'password_confirmation', 'type' => 'string', 'rules' => 'required', 'description' => 'Password confirmation'],
                    ],
                    'post_route' => 'POST /register -> CandidateWebController@registerUser',
                ],
            ],
            'Candidate (auth)' => [
                [
                    'id' => 'verify-otp',
                    'method' => 'GET',
                    'uri' => '/verify-email',
                    'name' => 'candidate.otp.view',
                    'middleware' => ['auth', 'role:candidate'],
                    'view' => 'auth/verify-otp.blade.php',
                    'controller' => 'Web\CandidateWebController',
                    'action' => 'showOtpForm',
                    'description' => 'Email OTP verification page shown immediately after account registration and before candidate profile submission.',
                    'variables' => [],
                    'models' => ['User', 'EmailVerificationOtp'],
                    'post_fields' => [
                        ['name' => 'otp', 'type' => 'string', 'rules' => 'required|digits:6', 'description' => 'Six digit OTP code sent to email'],
                    ],
                    'post_route' => 'POST /verify-email -> CandidateWebController@verifyOtp',
                    'also_posts' => [
                        [
                            'label' => 'Resend OTP',
                            'post_route' => 'POST /verify-email/resend -> CandidateWebController@resendOtp',
                            'post_fields' => [],
                        ],
                    ],
                ],
                [
                    'id' => 'register-stage2',
                    'method' => 'GET',
                    'uri' => '/register-candidate',
                    'name' => 'candidate.register.view',
                    'middleware' => ['auth', 'role:candidate'],
                    'view' => 'candidate/register.blade.php',
                    'controller' => 'Web\CandidateWebController',
                    'action' => 'showCandidateRegisterForm',
                    'description' => 'Verified candidates submit the full registration profile, including repeatable education, organization, committee, skill, and facility sections.',
                    'variables' => [
                        ['name' => '$departments', 'type' => 'Collection<Departmentsbiro>', 'description' => 'Active departments/biros for first and second choice selection.'],
                    ],
                    'models' => ['Candidate', 'Departmentsbiro', 'CandidateEducation', 'CandidateOrganization', 'CandidateCommittee', 'CandidateSkill', 'CandidateFacility'],
                    'post_fields' => [
                        ['name' => 'candidate_type', 'type' => 'string', 'rules' => 'required|in:staff,bph', 'description' => 'Registration type'],
                        ['name' => 'nickname', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Preferred nickname'],
                        ['name' => 'nim', 'type' => 'string', 'rules' => 'required|digits:10|unique:candidates', 'description' => 'Student ID number'],
                        ['name' => 'prodi', 'type' => 'string', 'rules' => 'required|in:3 valid values', 'description' => 'Study program'],
                        ['name' => 'kelas', 'type' => 'string', 'rules' => 'required|max:50', 'description' => 'Class name'],
                        ['name' => 'phone', 'type' => 'string', 'rules' => 'required|max:20', 'description' => 'Phone number'],
                        ['name' => 'address', 'type' => 'text', 'rules' => 'required', 'description' => 'Full address'],
                        ['name' => 'first_choice_id', 'type' => 'int', 'rules' => 'required|active departmentsbiro', 'description' => 'First choice department ID, stored in candidate_departmentsbiro'],
                        ['name' => 'second_choice_id', 'type' => 'int', 'rules' => 'nullable|different:first_choice_id|active departmentsbiro', 'description' => 'Second choice department ID, stored in candidate_departmentsbiro'],
                        ['name' => 'department_choice_reason', 'type' => 'text', 'rules' => 'required', 'description' => 'Combined reason for department choices'],
                        ['name' => 'weakness_description', 'type' => 'text', 'rules' => 'required', 'description' => 'Candidate self-evaluation of weaknesses'],
                        ['name' => 'contribution_plan', 'type' => 'text', 'rules' => 'required', 'description' => 'Concrete plan if selected'],
                        ['name' => 'photo', 'type' => 'image', 'rules' => 'required|jpg/png|max:1MB', 'description' => 'Candidate photo'],
                        ['name' => 'instagram_proof', 'type' => 'image', 'rules' => 'required|jpg/png|max:2MB', 'description' => 'Instagram follow proof'],
                        ['name' => 'youtube_proof', 'type' => 'image', 'rules' => 'required|jpg/png|max:2MB', 'description' => 'YouTube subscribe proof'],
                        ['name' => 'political_statement', 'type' => 'file', 'rules' => 'required|pdf/jpg/png|max:2MB', 'description' => 'Political statement letter'],
                        ['name' => 'candidate_signature', 'type' => 'image', 'rules' => 'required|jpg/png|max:2MB', 'description' => 'Candidate signature'],
                        ['name' => 'parent_signature', 'type' => 'image', 'rules' => 'required|jpg/png|max:2MB', 'description' => 'Parent signature'],
                        ['name' => 'educations[]', 'type' => 'array', 'rules' => 'nullable', 'description' => 'Education history rows'],
                        ['name' => 'organizations[]', 'type' => 'array', 'rules' => 'nullable', 'description' => 'External organization rows'],
                        ['name' => 'committees[]', 'type' => 'array', 'rules' => 'nullable', 'description' => 'Committee history rows'],
                        ['name' => 'skills[]', 'type' => 'array', 'rules' => 'nullable', 'description' => 'Skill rows'],
                        ['name' => 'facilities[]', 'type' => 'array', 'rules' => 'nullable', 'description' => 'Facility rows'],
                    ],
                    'post_route' => 'POST /register-candidate -> CandidateWebController@registerCandidate',
                ],
                [
                    'id' => 'schedule',
                    'method' => 'GET',
                    'uri' => '/schedule',
                    'name' => 'candidate.schedule.view',
                    'middleware' => ['auth', 'role:candidate'],
                    'view' => 'candidate/schedule.blade.php',
                    'controller' => 'Web\CandidateWebController',
                    'action' => 'showScheduleForm',
                    'description' => 'Candidate selects an available interview slot from their first-choice department after completing the profile. The same page doubles as the candidate status page later.',
                    'variables' => [
                        ['name' => '$candidate', 'type' => 'Candidate', 'description' => 'Authenticated candidate profile'],
                        ['name' => '$availableSlots', 'type' => 'Collection<InterviewSchedule>', 'description' => 'Unbooked active slots for the candidate first-choice department, plus their current slot'],
                        ['name' => '$announcement', 'type' => 'Announcement|null', 'description' => 'Final announcement if it exists'],
                        ['name' => '$dssResults', 'type' => 'array|null', 'description' => 'DSS score breakdown if published and evaluated'],
                    ],
                    'models' => ['Candidate', 'InterviewSchedule', 'Announcement', 'Departmentsbiro'],
                    'services' => ['ProfileMatchingService'],
                    'post_fields' => [
                        ['name' => 'schedule_id', 'type' => 'int', 'rules' => 'required|exists:interview_schedules', 'description' => 'Chosen interview schedule slot ID'],
                    ],
                    'post_route' => 'POST /schedule/book -> CandidateWebController@bookSchedule',
                ],
            ],
            'Interviewer (auth)' => [
                [
                    'id' => 'interviewer-dashboard',
                    'method' => 'GET',
                    'uri' => '/interviewer/schedule',
                    'name' => 'interviewer.schedule',
                    'middleware' => ['auth', 'role:interviewer'],
                    'view' => 'interviewer/dashboard.blade.php',
                    'controller' => 'Web\InterviewerWebController',
                    'action' => 'index',
                    'description' => 'Interviewer dashboard showing assigned department schedule slots with booked candidate details.',
                    'variables' => [
                        ['name' => '$schedules', 'type' => 'Collection<InterviewSchedule>', 'description' => 'Schedules assigned to the interviewer.'],
                    ],
                    'models' => ['InterviewSchedule', 'Candidate', 'User', 'Departmentsbiro'],
                    'post_fields' => [],
                ],
                [
                    'id' => 'interviewer-grade',
                    'method' => 'GET',
                    'uri' => '/interviewer/grade/{candidate}/{department}',
                    'name' => 'interviewer.grade.view',
                    'middleware' => ['auth', 'role:interviewer'],
                    'view' => 'interviewer/grade.blade.php',
                    'controller' => 'Web\InterviewerWebController',
                    'action' => 'showGradingForm',
                    'description' => 'Shared grading page for a specific candidate in a specific department. Multiple interviewers see one shared score row per criterion.',
                    'variables' => [
                        ['name' => '$candidate', 'type' => 'Candidate', 'description' => 'Candidate being graded.'],
                        ['name' => '$department', 'type' => 'Departmentsbiro', 'description' => 'Department grading context.'],
                        ['name' => '$criteria', 'type' => 'Collection<EvaluationCriteria>', 'description' => 'Department evaluation criteria.'],
                        ['name' => '$existingScores', 'type' => 'Collection', 'description' => 'Previously saved scores keyed by criteria ID.'],
                        ['name' => '$announcement', 'type' => 'Announcement|null', 'description' => 'Current candidate decision if any.'],
                        ['name' => '$departments', 'type' => 'Collection<Departmentsbiro>', 'description' => 'All departments for assignment dropdown.'],
                    ],
                    'models' => ['Candidate', 'Departmentsbiro', 'EvaluationCriteria', 'Evaluation', 'Announcement'],
                    'post_fields' => [
                        ['name' => 'scores[{criteria_id}]', 'type' => 'int', 'rules' => 'required|integer|min:1|max:5', 'description' => 'Score per criterion.'],
                    ],
                    'post_route' => 'POST /interviewer/grade/{candidate}/{department} -> InterviewerWebController@submitScores',
                    'also_posts' => [
                        [
                            'label' => 'Decision Form',
                            'post_route' => 'POST /interviewer/decide/{candidate} -> InterviewerWebController@decideCandidate',
                            'post_fields' => [
                                ['name' => 'status', 'type' => 'string', 'rules' => 'required|in:accepted,rejected', 'description' => 'Final decision'],
                                ['name' => 'assigned_department_id', 'type' => 'int', 'rules' => 'required_if:status,accepted', 'description' => 'Assigned department if accepted'],
                            ],
                        ],
                    ],
                ],
            ],
            'Admin (auth)' => [
                [
                    'id' => 'admin-dashboard',
                    'method' => 'GET',
                    'uri' => '/admin/dashboard',
                    'name' => 'admin.dashboard',
                    'middleware' => ['auth', 'role:admin'],
                    'view' => 'admin/dashboard.blade.php',
                    'controller' => 'Web\AdminWebController',
                    'action' => 'dashboard',
                    'description' => 'Admin overview with recruitment statistics, department CRUD, and announcement publish toggle.',
                    'variables' => [
                        ['name' => '$stats', 'type' => 'array', 'description' => 'Candidate counts by status.'],
                        ['name' => '$departments', 'type' => 'Collection<Departmentsbiro>', 'description' => 'Departments with first and second choice candidate counts.'],
                    ],
                    'models' => ['Candidate', 'Departmentsbiro'],
                    'post_fields' => [
                        ['name' => 'name', 'type' => 'string', 'rules' => 'required|unique:departmentsbiro', 'description' => 'Department name'],
                        ['name' => 'description', 'type' => 'string', 'rules' => 'nullable', 'description' => 'Description'],
                        ['name' => 'personal_aspect_weight', 'type' => 'decimal', 'rules' => 'required|0-100', 'description' => 'Personal aspect weight percentage'],
                        ['name' => 'organizational_aspect_weight', 'type' => 'decimal', 'rules' => 'required|0-100', 'description' => 'Organizational aspect weight percentage'],
                        ['name' => 'core_factor_weight', 'type' => 'decimal', 'rules' => 'required|0-100', 'description' => 'Core factor weight percentage'],
                        ['name' => 'secondary_factor_weight', 'type' => 'decimal', 'rules' => 'required|0-100', 'description' => 'Secondary factor weight percentage'],
                        ['name' => 'is_active', 'type' => 'boolean', 'rules' => 'optional', 'description' => 'Inactive departments are admin-only'],
                    ],
                    'post_route' => 'POST /admin/departments -> AdminWebController@storeDepartment',
                ],
                [
                    'id' => 'admin-rankings',
                    'method' => 'GET',
                    'uri' => '/admin/rankings/{department}',
                    'name' => 'admin.rankings',
                    'middleware' => ['auth', 'role:admin'],
                    'view' => 'admin/rankings.blade.php',
                    'controller' => 'Web\AdminWebController',
                    'action' => 'showRankings',
                    'description' => 'DSS ranking view for a department.',
                    'variables' => [
                        ['name' => '$department', 'type' => 'Departmentsbiro', 'description' => 'Department being ranked.'],
                        ['name' => '$rankings', 'type' => 'array', 'description' => 'Sorted DSS candidate rankings.'],
                        ['name' => '$announcements', 'type' => 'Collection<Announcement>', 'description' => 'Existing decisions keyed by candidate ID.'],
                    ],
                    'models' => ['Departmentsbiro', 'Candidate', 'Announcement'],
                    'services' => ['ProfileMatchingService'],
                    'post_fields' => [
                        ['name' => 'status', 'type' => 'string', 'rules' => 'required|in:accepted,rejected', 'description' => 'Decision for the candidate'],
                        ['name' => 'assigned_department_id', 'type' => 'int', 'rules' => 'required_if:status,accepted', 'description' => 'Assigned department if accepted'],
                    ],
                    'post_route' => 'POST /admin/decide/{candidate} -> AdminWebController@decideCandidate',
                ],
                [
                    'id' => 'admin-criteria',
                    'method' => 'GET',
                    'uri' => '/admin/criteria/{department}',
                    'name' => 'admin.criteria',
                    'middleware' => ['auth', 'role:admin'],
                    'view' => 'admin/criteria.blade.php',
                    'controller' => 'Web\AdminWebController',
                    'action' => 'listCriteria',
                    'description' => 'Manage evaluation criteria for a specific department.',
                    'variables' => [
                        ['name' => '$department', 'type' => 'Departmentsbiro', 'description' => 'Department whose criteria are being managed.'],
                        ['name' => '$criteria', 'type' => 'Collection<EvaluationCriteria>', 'description' => 'Department criteria.'],
                    ],
                    'models' => ['Departmentsbiro', 'EvaluationCriteria'],
                    'post_fields' => [
                        ['name' => 'name', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Criterion name'],
                        ['name' => 'type', 'type' => 'string', 'rules' => 'required|in:core,secondary', 'description' => 'Factor type'],
                        ['name' => 'target_score', 'type' => 'int', 'rules' => 'required|1-5', 'description' => 'Ideal score'],
                        ['name' => 'description', 'type' => 'string', 'rules' => 'nullable', 'description' => 'Description'],
                    ],
                    'post_route' => 'POST /admin/criteria/{department} -> AdminWebController@storeCriterion',
                ],
                [
                    'id' => 'admin-schedules',
                    'method' => 'GET',
                    'uri' => '/admin/schedules',
                    'name' => 'admin.schedules',
                    'middleware' => ['auth', 'role:admin'],
                    'view' => 'admin/schedules.blade.php',
                    'controller' => 'Web\AdminWebController',
                    'action' => 'listSchedules',
                    'description' => 'Full CRUD for interview schedule slots and interviewer assignment.',
                    'variables' => [
                        ['name' => '$schedules', 'type' => 'Collection<InterviewSchedule>', 'description' => 'All interview schedule slots with candidate and interviewer relations.'],
                        ['name' => '$interviewers', 'type' => 'Collection<User>', 'description' => 'All interviewer users.'],
                    ],
                    'models' => ['InterviewSchedule', 'Candidate', 'User'],
                    'post_fields' => [
                        ['name' => 'session_name', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Session name'],
                        ['name' => 'scheduled_at', 'type' => 'datetime', 'rules' => 'required|date', 'description' => 'Date and time of the session'],
                        ['name' => 'location', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Interview location'],
                        ['name' => 'interviewer_ids[]', 'type' => 'int[]', 'rules' => 'nullable|exists:users', 'description' => 'Assigned interviewer IDs'],
                    ],
                    'post_route' => 'POST /admin/schedules -> AdminWebController@storeSchedule',
                ],
                [
                    'id' => 'admin-interviewers',
                    'method' => 'GET',
                    'uri' => '/admin/interviewers',
                    'name' => 'admin.interviewers',
                    'middleware' => ['auth', 'role:admin'],
                    'view' => 'admin/interviewers.blade.php',
                    'controller' => 'Web\AdminWebController',
                    'action' => 'listInterviewers',
                    'description' => 'Full CRUD for interviewer accounts.',
                    'variables' => [
                        ['name' => '$interviewers', 'type' => 'Collection<User>', 'description' => 'All users with role interviewer.'],
                    ],
                    'models' => ['User'],
                    'post_fields' => [
                        ['name' => 'name', 'type' => 'string', 'rules' => 'required|max:255', 'description' => 'Full name'],
                        ['name' => 'email', 'type' => 'string', 'rules' => 'required|email|unique', 'description' => 'Email address'],
                        ['name' => 'password', 'type' => 'string', 'rules' => 'required|min:8', 'description' => 'Password'],
                    ],
                    'post_route' => 'POST /admin/interviewers -> AdminWebController@storeInterviewer',
                ],
            ],
        ];

        return view('docs.blade', compact('groups'));
    }
}
